Hf_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('account/', include('students.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views
from users import views as userstu

app_name= 'mainapp'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('gallery/', views.gallery, name= 'gallery'),
    path('about/', views.about, name= 'about'),
    path('faq/', views.faq, name= 'faq'),
    path('register/', userstu.register, name= 'register'),
    path('login/', userstu.loginUser, name= 'login'),
    path('logout/', authentication_views.LogoutView.as_view(next_page= 'mainapp:index'), name= 'logout'),
]

students/urls.py
from django.urls import path
from . import views

app_name= 'students'

urlpatterns = [
    path('dashboard', views.index, name= 'home'),
    path('election', views.election, name= 'election'),
    path('events', views.events, name= 'events'),
    path('advert', views.advert, name= 'advert'),
    path('issues', views.issues, name= 'issues'),
    path('payment', views.payments, name= 'payment'),
    path('profile', views.users_profiles, name= 'profile'),
    #path('/election', views.election, name= 'election'),
]

students/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNo = models.CharField(max_length=15, null=True, blank=True)
    roomId = models.CharField(max_length=10, null=True, blank=True)
    department = models.CharField(max_length=40, null= True, blank=True)
    image = models.ImageField(default= 'mike.png', upload_to= 'images', blank= True)
    lga = models.CharField(max_length=40, null= True, blank=True)
    stage_origin = models.CharField(max_length=40, null= True, blank=True)
    religion = models.CharField(max_length=40, null= True, blank=True)
    reg_no = models.CharField(max_length=40, null= True, blank=True)
    
    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()
        
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name', 'required': True, 'id': 'firstName'}))
    #first_name = forms.CharField(max_length=30, required=True, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'UserName', 'required': True, 'id': 'userName'}))
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name', 'required': True, 'id': 'lastName'}))
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', widget= forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email', 'required': True, 'id': 'email'}))
    phoneNo = forms.CharField(max_length=15,widget= forms.TextInput(attrs= {'class': 'form-control', 'placeholder': 'Phone No', 'required': True, 'id': 'phoneNo'}))
    roomId = forms.CharField(max_length=10, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Room Id', 'id': 'roomId', 'required': True}))
    password1 = forms.CharField(required=True, widget= forms.PasswordInput(attrs= {'class': 'form-control', 'id': 'create-password', 'required': True, 'placeholder': 'Create Password'}))
    password2 = forms.CharField(required=True, widget= forms.PasswordInput(attrs= {'class': 'form-control', 'id': 'con-password', 'required': True, 'placeholder': 'Confirm Password'}))
    
    class Meta:
        model = User
        fields = ('username', 'last_name', 'phoneNo', 'roomId', 'email', 'password1', 'password2')

mainapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'mainapp/index.html')

def gallery(request):
    return render(request, 'mainapp/gallery.html')

def faq(request):
    return render(request, 'mainapp/faq.html')

def about(request):
    return render(request, 'mainapp/about.html')

students/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
# Create your views here.

@login_required
def index(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user,
    }
    return render(request, 'students/index.html', context)

@login_required
def election(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user,
    }
    return render(request,'students/election.html')

@login_required
def advert(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user,
    }
    return render(request,'students/adverts.html')

@login_required
def events(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user,
    }
    return render(request,'students/events.html')

@login_required
def issues(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user,
    }
    return render(request,'students/issues.html')

@login_required
def payments(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user,
    }
    return render(request,'students/payment.html')

@login_required
def users_profiles(request):
    user = User.objects.get(username=request.user)
    context = {
        'user': user,
    }
    return render(request,'students/users-profile.html')

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import SignUpForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.roomId = form.cleaned_data.get('roomId')
            user.profile.phoneNo = form.cleaned_data.get('phoneNo')
            user.first_name = form.cleaned_data.get('username')
            user.save()
            messages.success(request, 'Profile created successfully')
            return redirect('/login')
        else:
            messages.error(request, 'Invalid username or password')
    else:
        form = SignUpForm()
    return render(request, 'mainapp/register.html',{'form': form})

def loginUser(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('students:home')  # Redirect to student/admin account
        else:
            messages.error(request, 'Invalid Username or Password')
            return redirect('/login')
    return render(request, 'mainapp/login.html')

mainapp/templates/mainapp/about.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block content %}

<!-- About HF -->
<div class="outer">
    <div class="row m-1">
        <div class="col justified-content-center my-md-4 text-center align-item-center">
            <h2 class="sub-head font-color">About</h2>
        </div>
    </div>

    <div class="border-1">
        <h3>LOCATION:</h3>

        <p>Amansea in Awka North LGA Anambra State.</p>

        <h3>STRUCTURE AND FEATURES:</h3>

        <p> Four gigantic twin hostels with private kitchens, laundry, water heaters and study rooms; chapel; a
            cyber cafe; a clinic; a supermarket; hair saloon; General kitchen; canteen and refectory; a generator
            house with solar panels; two 740ft scientific boreholes for water; police post for security; football
            pitch; lawn tennis courts; basket and volleyball courts</p>

        <h3>CAPACITY AND LOGISTICS:</h3>

        <p>The hostel has 504 rooms in all. 492 are fully occupied by students both males and females though
            separately. The hostel has a total of 984 students from every part of Nigeria and different religious
            denominations. It is managed by three priests (The Rector, Spiritual Director and Bursar) and six
            religious sisters.</p>

        <h3>INAUGURATION:</h3>

        <p>14th September 2009.</p>

        <h3>VISION:</h3>

        <p>Formation of future leaders through selfless and exemplary services.</p>

        <h3>MISSION:</h3>

        <p>Provision of a very conducive and serene atmosphere for studies and to get the best out of the youths in
            order to arm them to face future challenges, realize their dreams and help in transforming our society.
        </p>

        <h3>FEATS SO FAR:</h3>

        <p>Overall best hostel in cleanliness and discipline 2009 till date; overall best in academics and sports.
        </p>

        <h3>CONTACTS:</h3>
        <ul>
            <li> Fr. Obielosi Dominic (The Rector): 08032776139.</li>

            <li>Fr. Ogbuowelu Emmanuel (The Bursar): 08167676299.</li>

            <li>Sis. M. Sarah Edeoga (The Chief Receptionist): 08064689745.</li>
        </ul>
    </div>

</div>

{% endblock content %}

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en-UK">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HFYV</title>
    <link rel="shortcut icon" href="{% static 'mainapp/assets/hflogo.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'mainapp/css/style.css' %}">
    <script src="https://kit.fontawesome.com/e918c11bd2.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- Aos animation style -->
    <!-- <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"> -->
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <!-- Navigation Menu -->
    <nav class="navbar navbar-expand-lg bg-light sticky-top navbar-light py-2 shadow">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="{% static 'mainapp/assets/hflogo.png' %}" alt="Holy family logo" height= "60px">
            </a>
            <button class="navbar-toggler shadow-sm" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fas fa-stream m-2"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="modal" data-bs-target="#exampleModal" href="#">How To Book</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:gallery' %}">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:faq' %}">FAQ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'mainapp:login' %}" class="btn px-2 mx-2 nav-link btn-pri">Login</a>
                    </li>
            </div>
        </div>
    </nav>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">How To Book</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>1. Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
                    <p>2. Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
                    <p>3. Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
                    <p>4. Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
                    <p>5. Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
                </div>
            </div>
        </div>
    </div>

    {% block content %}
    
    {% endblock content %}

        <!--     Footer      -->
    <footer class=" bg-dark text-white pt-3 pb-2">
        <div class="container text-md-left">
            
            <div class="row text-md-left">

                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-1">
                    <img src="{% static 'mainapp/assets/hflogo.png' %}" alt="holy family logo" class="lg-sz" srcset="">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warnimg">Holy Family Youth Village</h5>
                </div>

                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-2">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Product</h5>
                    <p><a href="#" class="text-white toltip">Hub</a></p>
                    <p><a href="#" class="text-white toltip">Accomodation</a></p>
                    <p><a href="#" class="text-white toltip">Community</a></p>
                </div>
                
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-2">
                    <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Contact</h5>
                    <p><i class="fas fa-home me-3"></i> Amansea, Anambra State</p>
                    <p><i class="fas fa-envelope me-3"></i> info.hfyv@gmail.com</p>
                    <p><i class="fas fa-phone me-3"></i> +234 8064689745</p>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                    <p class="text-center"><a href="{% url 'mainapp:login' %}" class="btn btn-pri brn mx-3 shadow">Login</a></p>
                    <p  class="text-center"><a href="{% url 'mainapp:register' %}" class="btn brn btn-sec shadow">Register</a></p>
                    
                </div>

            </div>
            <hr class="mb-2">
            <div class="row align-items-center">

                <div class="col-md-7 col-lg-8">
                    <p>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> 2020 All rights reserved by:
                        <a href="#" target="_blank" class="toltip" rel="noopener noreferrer">
                            <strong class="text-warning">Bravta Code</strong>
                        </a>
                    </p>
                </div>

                <div class="col-md-5 col-lg-4">
                    <div class="text-center text-md-right">
                        <ul class="list-unstyled list-inline">
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm socialz text-white"><i class="fab fa-facebook"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm socialz text-white"><i class="fab fa-whatsapp"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm socialz text-white"><i class="fab fa-linkedin"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#" class="btn-floating btn-sm socialz text-white"><i class="fab fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    
    <!-- aos animation.js -->
    <!-- <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script> -->
    <script src="{% static 'mainapp/Js/script.js' %}"></script>
</body>
</html>

students/templates/students/election.html
{% extends 'students/base.html' %}
{% load static %}

  <!-- ======= Sidebar ======= -->
  {% block nav %}
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link active collapsed" href="{% url 'students:home' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:events' %}">
          <i class="bi bi-calendar-event"></i>
          <span>Events</span>
        </a>
      </li><!-- End Event Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:payment' %}">
          <i class="bi bi-credit-card"></i>
          <span>Payment</span>
        </a>
      </li><!-- End Payment Page Nav -->
      
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-badge-ad"></i><span>Advert</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Recent Advert</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Add Advert</span>
            </a>
          </li>
        </ul>
      </li><!-- End Advert Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:issues' %}">
          <i class="bi bi-exclamation-octagon"></i>
          <span>Report Issues</span>
        </a>
      </li><!-- End Report Issue Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:profile' %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="bi bi-check2-square"></i>
          <span>Election</span>
        </a>
      </li><!-- End Election page Nav -->

      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="pages-blank.html">
          <i class="bi bi-file-earmark"></i>
          <span>Blank</span>
        </a>
      </li> End Blank Page Nav -->

    </ul>

  </aside>
  {% endblock nav %}
  <!-- End Sidebar-->

  <!-- ======= Menu ======= -->
  {% block content %}
  <main id="main" class="main">
    <div class="container">

      <section class="section error-404 min-vh-100 d-flex flex-column align-items-center justify-content-center">
        <h1>404</h1>
        <h2>The page you are looking for is currently unavailable.</h2>
        <a class="btn" href="index.html">Back to home</a>
        <img src="{% static 'students/assets/img/not-found.svg' %}" class="img-fluid py-5" alt="Page Not Found">
      </section>

    </div>
  </main>
  {% endblock content %}
  <!-- End #main -->

students/templates/students/index.html
{% extends 'students/base.html' %}
{% load static %}

  <!-- ======= Sidebar ======= -->
  {% block nav %}
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="#">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:events' %}">
          <i class="bi bi-calendar-event"></i>
          <span>Events</span>
        </a>
      </li><!-- End Event Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:payment' %}">
          <i class="bi bi-credit-card"></i>
          <span>Payment</span>
        </a>
      </li><!-- End Payment Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-badge-ad"></i><span>Advert</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Recent Advert</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="bi bi-circle"></i><span>Add Advert</span>
            </a>
          </li>
        </ul>
      </li><!-- End Advert Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:issues' %}">
          <i class="bi bi-exclamation-octagon"></i>
          <span>Report Issues</span>
        </a>
      </li><!-- End Report Issue Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:profile' %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'students:election' %}">
          <i class="bi bi-check2-square"></i>
          <span>Election</span>
        </a>
      </li><!-- End Election page Nav -->

      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="pages-blank.html">
          <i class="bi bi-file-earmark"></i>
          <span>Blank</span>
        </a>
      </li> End Blank Page Nav -->

    </ul>

  </aside>
  {% endblock nav %}
  <!-- End Sidebar-->

  <!-- ======= Main`` ======= -->
  {% block content %}
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'students:home' %}">Home</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">

        <!-- Sales Card -->
        <div class="col-xxl-4 col-md-4">
          <div class="card info-card sales-card">
            <div class="card-body">
              <h5 class="card-title">Room Number</h5>

              <div class="d-flex align-items-center">
                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <i class="bx bxs-bed"></i>
                </div>
                {% with room_id=user.profile.roomId %}
                {% with first_two=room_id|slice:"0:2" %}
                {% with last_two=room_id|slice:"-2:" %}
                <div class="ps-3">
                  <h6>{{ first_two|upper }} <span class="text-warning pt-1 fw-bold">/ {{ last_two }}</span></h6>
                </div>
                {% endwith %}
                {% endwith %}
                {% endwith %}
              </div>
            </div>

          </div>
        </div><!-- End Sales Card -->

        <!--  Announcement  -->
        <div class="col-lg-8">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Recent Announcement</h5>
              <div class="accordion accordion-flush" id="accordionFlushExample">

                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                      Archbishop Visit
                    </button>
                  </h2>
                  <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facere earum, nam quia expedita blanditiis, hic quo facilis ipsum eius similique doloribus dolores nemo eaque voluptatem autem ratione, architecto a rem!</div>
                  </div>
                </div>

                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                      Hostel Maintenance
                    </button>
                  </h2>
                  <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum dolores laudantium ea molestias repudiandae sunt quas, doloribus quam quo. Animi quasi accusantium, eum in qui possimus magni ratione molestiae maxime!</div>
                  </div>
                </div>

                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                      Rent Renewal
                    </button>
                  </h2>
                  <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat, repellendus hic aperiam nam modi repudiandae velit nobis atque iste, possimus odit suscipit veritatis quo libero optio vel? Similique, quisquam explicabo.</div>
                  </div>
                </div>
              </div><!-- End Recent Announcement -->

            </div>
          </div>

        </div>
      </div>

      <!-- ====== card ====== -->
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Recent Announcement</h5>
              
              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Topic</th>
                    <th scope="col">Details</th>
                    <th scope="col">Date</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Archbishop Visit</td>
                    <td>Lorem ipsum dolor sit amet consectetur adipisicing elit.</td>
                    <td>2014-12-05</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Rent Renewal</td>
                    <td>Lorem ipsum dolor sit amet consectetur adipisicing elit.</td>
                    <td>2014-12-05</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td>Hostel Election</td>
                    <td>Lorem ipsum dolor sit amet consectetur adipisicing elit.</td>
                    <td>2011-08-12</td>
                  </tr>
                  <tr>
                    <th scope="row">4</th>
                    <td>Hostel Maintenance</td>
                    <td>Lorem ipsum dolor sit amet consectetur adipisicing elit.</td>
                    <td>2012-06-11</td>
                  </tr>
                  <tr>
                    <th scope="row">5</th>
                    <td>Block Party</td>
                    <td>Lorem ipsum dolor sit amet consectetur adipisicing elit.</td>
                    <td>2011-04-19</td>
                  </tr>
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>
        </div>

      </div>
    </section>

  </main>
  {% endblock content %}
  <!-- End #main -->
